### PR TITLE
remove blank code

### PR DESCRIPTION
**Pull request by duncandewhurst**
Addresses https://github.com/open-contracting/public-private-partnerships/issues/135

### CODE REVIEW

**Comment by jpmckinney** [comment]
@duncandewhurst Seems you need to update the `enum` in the JSON Schema.

**Comment by duncandewhurst** [comment]
Ah, thanks @jpmckinney, I've fixed that now

**Comment by jpmckinney** [comment]
It was also failing because `large` was not defined. I proposed a simple definition.

**Comment by jpmckinney** [comment]
The definition for `large` that I added is "This is a large enterprise according to the definitions used by the procuring entity or buyer." where everything after "This is a large enterprise" is the same text as the other definitions.

**Pull request merged**
